import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';
import { ReactQueryClientProvider } from '@/components/providers/react-query-client-provider';

const manrope = Manrope({ subsets: ['latin'], weight: ['500'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={manrope.className}>{children}</body>
      </html>
    </ReactQueryClientProvider>
  );
}
